### PR TITLE
Added remove()[Feature 3]

### PR DESCRIPTION
**Pull request by brodskye**
Added code for the remove function.

### CODE REVIEW

**Comment by elliotda** [comment]
If i'm not mistaken NULL needs to be null. When I imported your code locally to test it, NULL crashed. Also your code can be simplified, although not necessary. I'll talk to you in class later today about this.

**Comment by elliotda** [comment]
Also, please write a feature on this. :)

**Comment by elliotda** [comment]
Great! I'll accept the merge. I'll go over the simplified version of your code and if you like it, we can replace it later.

**Comment by brodskye** [comment]
Awesome :) we can talk in OS later today

**Pull request merged**
